CREATE FUNCTION [dbo].[GetSocialNetworkColor]
(
	@Name VARCHAR(50)
)
RETURNS VARCHAR(7)
AS
BEGIN
	IF LOWER(@Name) = 'twitter'
		return '#218C94'
    IF LOWER(@Name) = 'facebook'	  
		return '#3B5A9C'
	IF LOWER(@Name) = 'linkedin'
		return '#006B9C'
	IF LOWER(@Name) = 'google'
		return '#A40000'
	IF LOWER(@Name) = 'myspace'
		return '#214A94'
	IF LOWER(@Name) = 'digg'
		return '#082142'
	IF LOWER(@Name) = 'delicious'
		return '#666666'
	IF LOWER(@Name) = 'blogger'
		return '#C55208'
	IF LOWER(@Name) = 'tumblr'
		return '#113144'
	IF LOWER(@Name) = 'technorati'
		return '#5BAC28'
	IF LOWER(@Name) = 'stumbleupon'
		return '#53B552'
	IF LOWER(@Name) = 'reddit'
		return '#FF3300'
	IF LOWER(@Name) = 'posterous'
		return '#735A29'
	IF LOWER(@Name) = 'orkut'
		return '#B52994'
	IF LOWER(@Name) = 'windows live'
		return '#6395B4'
	IF LOWER(@Name) = 'meneame'
		return '#EF6A3A'
	IF LOWER(@Name) = 'viadeo'
		return '#F6AB44'
	IF LOWER(@Name) = 'other'
		return '#CCCCCC'
	IF LOWER(@Name) = 'googlemas'
		return '#910101'
	IF LOWER(@Name) = 'pinterest'	
		return '#F90101'
	return '#FFFFFF'
END