CREATE NONCLUSTERED INDEX [IX_Campaign_Status]
    ON [dbo].[Campaign]([Status] ASC, [Queued] ASC, [TestABCategory] ASC)
    INCLUDE([IdCampaign], [UTCScheduleDate], [UTCSentDate], [IdTestAB]) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [Campaign];



