CREATE NONCLUSTERED INDEX [IX_LinkTracking_IdSubscriber]
    ON [dbo].[LinkTracking]([IdSubscriber] ASC, [IdLink] ASC)
    INCLUDE([Count]) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [Campaign];


