CREATE UNIQUE NONCLUSTERED INDEX [IX_ParentCampaign]
	ON [dbo].[Campaign] 
	(
		[IdParentCampaign] ASC
	)
	WHERE ([IdParentCampaign] IS NOT NULL) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
	ON [PRIMARY]
