CREATE NONCLUSTERED INDEX [IX_SubscribersList_IdUser]
    ON [dbo].[SubscribersList]([IdUser] ASC, [Active] ASC, [Visible] ASC)
    INCLUDE([IdLabel]) WITH (FILLFACTOR = 99, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [SubscriberList];



