CREATE NONCLUSTERED INDEX [IX_SubscriberBlackList_Marked]
    ON [dbo].[SubscriberBlackList]([Marked] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = ON, ONLINE = OFF, MAXDOP = 0)
    ON [Subscriber];





