ALTER TABLE [dbo].[CreditCardTypes]
    ADD CONSTRAINT [PK__CreditCardTypes__42ACE4D4] PRIMARY KEY NONCLUSTERED ([IdCCType] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];



