ALTER TABLE [dbo].[AdminOptionXQuestion]
    ADD CONSTRAINT [PK_AdminOptionXQuestion] PRIMARY KEY CLUSTERED ([IdOption] ASC, [IdQuestion] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
