ALTER TABLE [dbo].[AdminQuestionOption]
    ADD CONSTRAINT [PK_AdminQuestionOption] PRIMARY KEY CLUSTERED ([IdOption] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
