ALTER TABLE [dbo].[AdminAccessRight]
    ADD CONSTRAINT [PK_AdminAccessRight] PRIMARY KEY CLUSTERED ([IdAdmin] ASC, [IdSection] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



