/*ALTER TABLE [dbo].[BlackListDomain]
    ADD CONSTRAINT [PK_BlackListDomain] PRIMARY KEY CLUSTERED ([Domain] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)*/

