ALTER TABLE [dbo].[BlackListSource]
    ADD CONSTRAINT [PK_BlackListSource] PRIMARY KEY CLUSTERED ([IdSource] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)

