ALTER TABLE [dbo].[ClientManagerUpgrade]
    ADD CONSTRAINT [PK_ClientManagerUpgrade] PRIMARY KEY CLUSTERED ([IdUserTypePlan] ASC, [IdClientManager] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



