ALTER TABLE [dbo].[CampaignBig]
    ADD CONSTRAINT [PK_CampaignBig] PRIMARY KEY CLUSTERED ([IDCampaign] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);







