ALTER TABLE [dbo].[CampaignDeliveriesOpenInfo]
    ADD CONSTRAINT [PK_CampaignDeliveriesOpenInfo] PRIMARY KEY CLUSTERED ([IdCampaign] ASC, [IdSubscriber] ASC) WITH (FILLFACTOR = 98, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



