ALTER TABLE [dbo].[UserTypes]
    ADD CONSTRAINT [PK_ClientTypes] PRIMARY KEY CLUSTERED ([IdUserType] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



