ALTER TABLE [dbo].[CampaignXSubscriberStatus]
    ADD CONSTRAINT [PK_CampaignXSubscriberStatus] PRIMARY KEY CLUSTERED ([IdCampaign] ASC, [IdSubscriber] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



