ALTER TABLE [dbo].[City]
    ADD CONSTRAINT [PK_City2] PRIMARY KEY CLUSTERED ([IdCity] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



