ALTER TABLE [dbo].[DMSSenderConfig]
ADD CONSTRAINT [PK_DMSSenderConfig] PRIMARY KEY CLUSTERED ([IdDMSSenderConfig] ASC, [Type] ASC, IdDMS ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
