ALTER TABLE [dbo].[DMSConfig]
ADD CONSTRAINT [PK_DMSConfig] PRIMARY KEY CLUSTERED ([IdDMS] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
