ALTER TABLE [dbo].[DomainKeyInformation]
    ADD CONSTRAINT [PK_DomainKeyInformation] PRIMARY KEY CLUSTERED ([IdUser] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



