ALTER TABLE [dbo].[DMSSenderInfoConfig]
ADD CONSTRAINT [PK_DMSSenderInfoConfig] PRIMARY KEY CLUSTERED ([IdDMSSenderInfoConfig] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
