ALTER TABLE [dbo].[FieldMapping]
    ADD CONSTRAINT [PK_FieldMapping] PRIMARY KEY CLUSTERED ([IdFieldMapping] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



