ALTER TABLE [dbo].[FilterBySubscribersList]
    ADD CONSTRAINT [PK_FilterBySubscribersList] PRIMARY KEY CLUSTERED ([IdFilter] ASC, [IdSubscribersLists] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



