ALTER TABLE [dbo].[FilterByCampaignDeliveries]
    ADD CONSTRAINT [PK_FilterByCampaignDeliveries] PRIMARY KEY CLUSTERED ([IdFilter] ASC, [IdCampaign] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



