ALTER TABLE [dbo].[FormPendingConfirmation]
    ADD CONSTRAINT [PK_FormPendingConfirmation] PRIMARY KEY NONCLUSTERED ([IdFormPendingConfirmation] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];





