ALTER TABLE [dbo].[Filter]
    ADD CONSTRAINT [PK_Filter] PRIMARY KEY CLUSTERED ([IdFilter] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



