ALTER TABLE [dbo].[ForwardFriend]
    ADD CONSTRAINT [PK_ForwardFriend] PRIMARY KEY CLUSTERED ([ForwardID] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



