ALTER TABLE [dbo].[FunctionRequestByIp]
    ADD CONSTRAINT [PK_FunctionRequestByIp] PRIMARY KEY CLUSTERED ([SourceIPAddress] ASC, [FunctionRequested] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



