ALTER TABLE [dbo].[FieldXSubscriber]
    ADD CONSTRAINT [PK_FieldXSubscriber] PRIMARY KEY CLUSTERED ([IdField] ASC, [IdSubscriber] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



