ALTER TABLE [dbo].[FieldXForm]
    ADD CONSTRAINT [PK_FieldXForm] PRIMARY KEY CLUSTERED ([IdField] ASC, [IdForm] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



