ALTER TABLE [dbo].[GireReportVersion]
    ADD CONSTRAINT [PK_GireReportVersion] PRIMARY KEY CLUSTERED ([Date] ASC, [Version] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

