ALTER TABLE [dbo].[HTMLTemplateXContent]
    ADD CONSTRAINT [PK_HTMLTemplateXContent] PRIMARY KEY CLUSTERED ([IdHTMLTemplate] ASC, [IdContent] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



