ALTER TABLE [dbo].[SocialNetworkShareXCampaign]
    ADD CONSTRAINT [PK_IdSocialNetwork] PRIMARY KEY CLUSTERED ([IdCampaign] ASC, [IdSocialNetwork] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



