ALTER TABLE [dbo].[LinkTracking]
    ADD CONSTRAINT [PK_LinkTracking] PRIMARY KEY NONCLUSTERED ([IdLinkTracking] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [Campaign];




