ALTER TABLE [dbo].[Link]
    ADD CONSTRAINT [PK_Link] PRIMARY KEY CLUSTERED ([IdLink] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



