ALTER TABLE [dbo].[MailConfirmation]
    ADD CONSTRAINT [PK_MailConfirmationList] PRIMARY KEY NONCLUSTERED ([IdMailConfirmation] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];





