/*ALTER TABLE [dbo].[NewFunctionalityPopup]
    ADD CONSTRAINT [PK_NewFunctionalityPopup] PRIMARY KEY CLUSTERED ([IdNewFunctionalityPopup] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

