ALTER TABLE [dbo].[PlatformTypes]
    ADD CONSTRAINT [PK_PlatformTypes] PRIMARY KEY CLUSTERED ([IdPlatformType] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



