/*ALTER TABLE [dbo].[PaymentMethodXCountry]
    ADD CONSTRAINT [PK_PaymentMethodXCountry] PRIMARY KEY CLUSTERED ([IdPaymentMethod] ASC, [IdCountry] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

