ALTER TABLE [dbo].[ResponsabileBilling]
    ADD CONSTRAINT [PK_ResponsabileBilling] PRIMARY KEY CLUSTERED ([IdResponsabileBilling] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



