ALTER TABLE [dbo].[ReportExportHeader]
    ADD CONSTRAINT [PK_ReportExportHeader] PRIMARY KEY CLUSTERED ([Description] ASC, [IdReportType] ASC, [IdLanguage] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

