ALTER TABLE [dbo].[Resource]
    ADD CONSTRAINT [PK_Resource] PRIMARY KEY CLUSTERED ([IdResource] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
