ALTER TABLE [dbo].[ReportRequest]
    ADD CONSTRAINT [PK_ReportRequest] PRIMARY KEY CLUSTERED ([IdRequest] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


