ALTER TABLE [dbo].[SecurityQuestion]
    ADD CONSTRAINT [PK_SecurityQuestion] PRIMARY KEY CLUSTERED ([IdSecurityQuestion] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



