ALTER TABLE [dbo].[SocialNetworkShareXUser]
    ADD CONSTRAINT [PK_SocialNetworkXUser_1] PRIMARY KEY CLUSTERED ([IdUser] ASC, [IdSocialNetwork] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



