ALTER TABLE [dbo].[SubscriberStatus]
    ADD CONSTRAINT [PK_SubscriberStatus] PRIMARY KEY CLUSTERED ([IdSubscriberStatus] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



