ALTER TABLE [dbo].[SocialNetworkShareTracking]
    ADD CONSTRAINT [PK_SocialNetworkShareTracking] PRIMARY KEY NONCLUSTERED ([IdSocialNetworkShareTracking] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [Campaign];



