ALTER TABLE [dbo].[Setting]
    ADD CONSTRAINT [PK_Setting] PRIMARY KEY CLUSTERED ([IdSetting] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



