ALTER TABLE [dbo].[SocialNetworkExtras]
    ADD CONSTRAINT [PK_SocialNetworkExtras_1] PRIMARY KEY CLUSTERED ([IdExtra] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



