ALTER TABLE [dbo].[SubscriberXList]
    ADD CONSTRAINT [PK_SubscriberXList] PRIMARY KEY CLUSTERED ([IdSubscribersList] ASC, [IdSubscriber] ASC) WITH (FILLFACTOR = 98, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



