ALTER TABLE [dbo].[SocialNetworkExtrasXUser]
    ADD CONSTRAINT [PK_SocialNetworkExtrasXUser] PRIMARY KEY CLUSTERED ([IdUser] ASC, [IdExtra] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



