ALTER TABLE [dbo].[SubscriberSourceType]
    ADD CONSTRAINT [PK_SubscriberSourceType] PRIMARY KEY CLUSTERED ([IdSubscriberSourceType] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



