ALTER TABLE [dbo].[SubscribersListXCampaign]
    ADD CONSTRAINT [PK_SubscribersListXCampaign] PRIMARY KEY CLUSTERED ([IdCampaign] ASC, [IdSubscribersList] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



