ALTER TABLE [dbo].[TestCriteria]
    ADD CONSTRAINT [PK_TestCriteria] PRIMARY KEY CLUSTERED ([IdCriteria] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



