ALTER TABLE [dbo].[TestABSubscriberList]
    ADD CONSTRAINT [PK_TestABSubscriberList] PRIMARY KEY CLUSTERED ([IdTestAB] ASC, [IdSubscriberList] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



