ALTER TABLE [dbo].[TestAB]
    ADD CONSTRAINT [PK_TestAB_1] PRIMARY KEY CLUSTERED ([IdTestAB] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



