ALTER TABLE [dbo].[UserChangesHistory]
    ADD CONSTRAINT [PK_UserChangesHistory] PRIMARY KEY CLUSTERED ([IdUserChangesHistory] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



