ALTER TABLE [dbo].[ViewerAccessRightXUser]
    ADD CONSTRAINT [PK_ViewerAccessRightXUser] PRIMARY KEY CLUSTERED ([IdViewer] ASC, [IdUser] ASC, [IdSection] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);









