ALTER TABLE [dbo].[ViewerSection]
    ADD CONSTRAINT [PK_ViewerSection] PRIMARY KEY CLUSTERED ([IdSection] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



