ALTER TABLE [dbo].[Viewer]
    ADD CONSTRAINT [UQ_Viewer] UNIQUE NONCLUSTERED ([Username] ASC, [IdClientManager] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];



