CREATE TABLE [dbo].[Form] (
    [WelcomeBodyType]           VARCHAR (10)  NULL,
    [ConfirmationBodyType]      VARCHAR (10)  NULL,
    [IdForm]                    INT           IDENTITY (5000, 1) NOT NULL,
    [IdUser]                    INT           NOT NULL,
    [Name]                      VARCHAR (50)  NULL,
    [UTCCreationDate]           DATETIME      NULL,
    [IdSubscribersList]         INT           NULL,
    [Title]                     VARCHAR (50)  NULL,
    [SubTitle]                  VARCHAR (50)  NULL,
    [Logo]                      NVARCHAR (50) NULL,
    [Font]                      VARCHAR (50)  NULL,
    [FontSize]                  INT           NULL,
    [IsBoldFont]                BIT           NULL,
    [IsItalicFont]              BIT           NULL,
    [IsUnderLineFont]           BIT           NULL,
    [IsStrikeThroughFont]       BIT           NULL,
    [FontColor]                 VARCHAR (50)  NULL,
    [TextAlign]                 VARCHAR (50)  NULL,
    [BackColor]                 VARCHAR (50)  NULL,
    [BackWidth]                 INT           NULL,
    [BackHeigth]                INT           NULL,
    [ButtonText]                VARCHAR (50)  NULL,
    [ButtonFont]                VARCHAR (50)  NULL,
    [ButtonFontSize]            INT           NULL,
    [IsButtonFontBold]          BIT           NULL,
    [IsButtonFontItalic]        BIT           NULL,
    [IsButtonUnderLine]         BIT           NULL,
    [ButtonFontColor]           VARCHAR (50)  NULL,
    [ButtonBackColor]           VARCHAR (50)  NULL,
    [ConfirmationType]          VARCHAR (50)  NULL,
    [PublicURL]                 VARCHAR (50)  NULL,
    [IsShowMessageSelected]     BIT           NULL,
    [URL]                       VARCHAR (250) NULL,
    [Message]                   VARCHAR (250) NULL,
    [DoubleOptInType]           VARCHAR (20)  NULL,
    [IsAdvancedSelected]        BIT           NULL,
    [ActivationMailHtmlContent] VARCHAR (400) NULL,
    [WelcomeMailHtmlContent]    VARCHAR (400) NULL,
    [LandingMessage]            VARCHAR (400) NULL,
    [HasLandingLogo]            BIT           NULL,
    [IdConfirmationMessage]     INT           NULL,
    [IdWelcomeMessage]          INT           NULL,
    [IsButtonStrikeThrough]     BIT           NULL,
    [IdMailTemplatesLanguage]   INT           NOT NULL,
    [ButtonAlign]               VARCHAR (50)  NULL
);





